language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# Travis CI서버의 홈
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean bootJar"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - ib.parksw@gmail.com