spring:
  profiles:
    include: oauth
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
  session:
    store-type: jdbc
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
